### ISSUE TITLE
how to disable the touchhints?

### ISSUE THREAD

**Issue by HankMonster** [unixzii/CVTouchHints#2]
It is a great tool for making screen recording more powerful. The only issue I have is:
Is there any way to turn on/off the hints on demand by the user?

Thanks a lot!

**Comment by unixzii** [comment]
I'm glade to hear that you like it. This utility is made for helping developers to make screen cast to advertise or demonstrate their products, it's not with the purpose of delivering to end-users, because, it did intercept the process events dispatch and can lead to potential issues.

But as a workaround, you can try modifying it by grabbing its overlay window, and set its `hidden` or `alpha` manually.
